select max(reflenderconfigid) from staging.ref_lender_config;
-- As for 6 and 7 with occupationtypeid = 1 in ref_lender_config was missing, inserted by Priyaraj on 20th March 2023
-- producttypeid = 6 and occupationtypeid = 1
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3115', '0', '1', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '6', '1', '1');
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3116', '0', '2', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '6', '1', '1');
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3117', '0', '3', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '6', '1', '1');
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3118', '0', '4', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '6', '1', '1');
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3119', '0', '1', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '6', '1', '0');
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3120', '0', '2', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '6', '1', '0');
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3121', '0', '3', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '6', '1', '0');
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3122', '0', '4', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '6', '1', '0');
-- producttypeid = 7 and occupationtypeid = 1
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3123', '0', '1', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '7', '1', '1');
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3124', '0', '2', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '7', '1', '1');
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3125', '0', '3', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '7', '1', '1');
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3126', '0', '4', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '7', '1', '1');
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3127', '0', '1', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '7', '1', '0');
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3128', '0', '2', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '7', '1', '0');
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3129', '0', '3', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '7', '1', '0');
INSERT INTO `staging`.`ref_lender_config` (`reflenderconfigid`, `lenderId`, `cityTierId`, `lendingcategoryid`, `minimumLendingAmount`, `maximumLendingAmount`, `minimumEarningsAmount`, `minimumJobExperience`, `minimumProfExperience`, `maximumTenure`, `useGrossPay`, `minimumAge`, `maximumAge`, `maximumAgeAtMaturity`, `productTypeId`, `OccupationTypeId`, `Itfiled`) VALUES ('3130', '0', '4', '1', '0', '999999999', '0', '0', '0', '240', '0', '21', '99', '70', '7', '1', '0');

-- ref_emi_config-- Removed the existing entries in ref_emi_config for lender 0 with respect to producttype 6
-- adding the entries similar to other producttypes for 6 with respect to lender 0
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('664', '6', '0', '25000', '40', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '1');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('665', '6', '0', '25000', '40', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '2');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('666', '6', '0', '25000', '40', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '3');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('667', '6', '25001', '50000', '50', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '1');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('668', '6', '25001', '50000', '50', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '2');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('669', '6', '25001', '50000', '50', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '3');

INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('670', '6', '50001', '100000', '50', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '1');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('671', '6', '50001', '100000', '50', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '2');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('672', '6', '50001', '100000', '50', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '3');

INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('673', '6', '100001', '99999999', '60', '0', '1', '0.00', '0', '3/20/2020 ', 'Vastu', '3/20/2020 ', 'Vastu', '1', '1');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('674', '6', '100001', '99999999', '60', '0', '1', '0.00', '0', '3/20/2020 ', 'Vastu', '3/20/2020 ', 'Vastu', '1', '2');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('675', '6', '100001', '99999999', '60', '0', '1', '0.00', '0', '3/20/2020 ', 'Vastu', '3/20/2020 ', 'Vastu', '1', '3');
-- ref_emi_config-- Removed the existing entries in ref_emi_config for lender 0 with respect to producttype 6
DELETE FROM `staging`.`ref_emi_config` WHERE (`emiConfigId` = '640');
DELETE FROM `staging`.`ref_emi_config` WHERE (`emiConfigId` = '642');

-- adding the entries similar to other producttypes for 7 with respect to lender 0
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('676', '7', '0', '25000', '40', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '1');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('677', '7', '0', '25000', '40', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '2');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('678', '7', '0', '25000', '40', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '3');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('679', '7', '25001', '50000', '50', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '1');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('680', '7', '25001', '50000', '50', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '2');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('681', '7', '25001', '50000', '50', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '3');

INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('682', '7', '50001', '100000', '50', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '1');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('683', '7', '50001', '100000', '50', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '2');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('684', '7', '50001', '100000', '50', '0', '1', '0.00', '0', '3/20/2023', 'Vastu', '3/20/2023', 'Vastu', '1', '3');

INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('685', '7', '100001', '99999999', '60', '0', '1', '0.00', '0', '3/20/2020 ', 'Vastu', '3/20/2020 ', 'Vastu', '1', '1');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('686', '7', '100001', '99999999', '60', '0', '1', '0.00', '0', '3/20/2020 ', 'Vastu', '3/20/2020 ', 'Vastu', '1', '2');
INSERT INTO `staging`.`ref_emi_config` (`emiConfigId`, `productTypeId`, `startRange`, `endRange`, `emiPercent`, `lenderId`, `referenceCategoryId`, `weightPct`, `score`, `createdOn`, `createdBy`, `updatedOn`, `updatedBy`, `activeStatus`, `OccupationTypeId`) VALUES ('687', '7', '100001', '99999999', '60', '0', '1', '0.00', '0', '3/20/2020 ', 'Vastu', '3/20/2020 ', 'Vastu', '1', '3');

UPDATE `staging`.`lender_product_loan` SET `producttypeforintcal` = '6' WHERE (`lenderproductloanid` = '250');
UPDATE `staging`.`lender_product_loan` SET `producttypeforintcal` = '6' WHERE (`lenderproductloanid` = '251');
UPDATE `staging`.`lender_product_loan` SET `producttypeforintcal` = '6' WHERE (`lenderproductloanid` = '252');
UPDATE `staging`.`lender_product_loan` SET `producttypeforintcal` = '6' WHERE (`lenderproductloanid` = '253');
UPDATE `staging`.`lender_product_loan` SET `producttypeforintcal` = '6' WHERE (`lenderproductloanid` = '254');

UPDATE `staging`.`lender_product_loan` SET `producttypeforintcal` = '7' WHERE (`lenderproductloanid` = '255');
UPDATE `staging`.`lender_product_loan` SET `producttypeforintcal` = '7' WHERE (`lenderproductloanid` = '256');
UPDATE `staging`.`lender_product_loan` SET `producttypeforintcal` = '7' WHERE (`lenderproductloanid` = '257');
UPDATE `staging`.`lender_product_loan` SET `producttypeforintcal` = '7' WHERE (`lenderproductloanid` = '258');
UPDATE `staging`.`lender_product_loan` SET `producttypeforintcal` = '7' WHERE (`lenderproductloanid` = '259');






