use staging;
SELECT max(loanLenderId) FROM staging.ref_loan_lender ;
-- provided on 30-03-2023. Inserted by Priyaraj 
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('238', 'Housing and urban Development Corporation Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('239', 'Indiabulls Housing Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('240', 'PNB Housing Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('241', 'Bajaj Housing Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('242', 'Tata Capital Housing Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('243', 'Can Fin Homes Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('244', 'IIFL Home Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('245', 'ICICI Home Finance Company Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('246', 'Aadhar Housing Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('247', 'Aditya Birla Housing Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('248', 'REPCO Home Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('249', 'GIC Housing Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('250', 'Aavas Financiers Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('251', 'Reliance Home Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('252', 'Sundaram Home Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('253', 'Mahindra Rural Housing Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('254', 'Shriram Housing Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('255', 'Aptus Value Housing Finance India Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('256', 'Home First Finance Company India Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('257', 'Fullerton India Home Finance Company Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('258', 'Poonawalla Housing Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('259', 'Edelweiss Housing Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('260', 'Hinduja Housing Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('261', 'Motilal Oswal Home Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('262', 'Vastu Housing Finance Corporation Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('263', 'India Shelter Finance Corporation Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('264', 'Hero Housing Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('265', 'Shubham Housing Development Finance Company', '1');

INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('266', 'Capri Global Housing Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('267', 'Godrej Housing Finance Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('268', 'Muthoot Housing Finance Company Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('269', 'IndoStar Home Finance Private Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('270', 'Muthoot Homefin (India) Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('271', 'Svatantra Micro Housing Finance Corporation Limited ', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('272', 'Cent Bank Home Finance Limited ', '1');

-- initially provided set
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('273', 'Karnataka Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('274', 'Karnataka Vikas Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('275', 'Kerala Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('276', 'Madhya Pradesh Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('277', 'Madhyanchal Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('278', 'Maharashtra Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('279', 'Manipur Rural Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('280', 'Meghalaya Rural Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('281', 'Mizoram Rural Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('282', 'Nagaland Rural Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('283', 'Odisha Gramya Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('284', 'Paschim Banga Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('285', 'Prathama U.P. Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('286', 'Puduvai Bharathiar Grama Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('287', 'Punjab Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('288', 'Rajasthan Marudhara Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('289', 'Saptagiri Grameena Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('290', 'Sarva Haryana Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('291', 'Saurashtra Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('292', 'Tamil Nadu Grama Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('293', 'Telangana Grameena Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('294', 'Tripura Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('295', 'Uttar Bihar Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('296', 'Utkal Grameen Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('297', 'Uttarbanga Kshetriya Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('298', 'Vidharbha Konkan Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('299', 'Uttarakhand Gramin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('300', 'AB Bank Ltd.', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('301', 'Abu Dhabi Commercial Bank PJSC', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('302', 'American Express Banking Corporation', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('303', 'Australia and New Zealand Banking Group Ltd.', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('304', 'Barclays Bank Plc.', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('305', 'Bank of America', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('306', 'Bank of Bahrain & Kuwait B.S.C.', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('307', 'Bank of Ceylon', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('308', 'Bank of China', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('309', 'Bank of Nova Scotia', '1');

INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('310', 'Citibank N.A.', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('311', 'Cooperatieve Rabobank U.A./ Coöperatieve Centrale Raiffeisen-Boerenleenbank B.A.', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('312', 'Credit Agricole Corporate & Investment Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('313', 'Credit Suisse AG', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('314', 'CTBC Bank Co., Ltd.', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('315', 'DBS Bank India Limited', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('316', 'Deutsche Bank A.G.', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('317', 'Doha Bank Q.P.S.C', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('318', 'Emirates NBD Bank PJSC', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('319', 'First Abu Dhabi Bank PJSC', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('320', 'FirstRand Bank Limited', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('321', 'Hong Kong and Shanghai Banking Corporation Limited', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('322', 'Industrial & Commercial Bank of China Ltd.', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('323', 'Industrial Bank of Korea', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('324', 'J.P. Morgan Chase Bank N.A.', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('325', 'JSC VTB Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('326', 'KEB Hana Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('327', 'Kookmin Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('328', 'Krung Thai Bank Public Co. Ltd. $', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('329', 'Mashreq bank PSC', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('330', 'Mizuho Bank Ltd.', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('331', 'MUFG Bank, Ltd.', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('332', 'NatWest Markets Plc', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('333', 'PT Bank Maybank Indonesia TBK', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('334', 'Qatar National Bank (Q.P.S.C.)', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('335', 'Sberbank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('336', 'SBM Bank (India) Limited', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('337', 'Shinhan Bank', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('338', 'Societe Generale India', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('339', 'Sonali Bank Ltd. %', '1');

INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('340', 'Sumitomo Mitsui Banking Corporation', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('341', 'United Overseas Bank Limited', '1');
INSERT INTO ref_loan_lender (loanLenderId, loanLenderName, activeStatus) VALUES ('342', 'Woori Bank', '1');
