CREATE TABLE PrimaryBank 
(
    BankName	VARCHAR(100),
    BankID	INT,
    activeStatus	VARCHAR(1),
    createdOn	VARCHAR(20),
    createdBy	VARCHAR(20)
);

INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('I dont have a bank account', '999', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('AB Bank Ltd.', '308', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Abu Dhabi Commercial Bank PJSC', '309', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Abu Dhabi Commercial Bank', '197', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Airtel Payments Bank', '256', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Allahabad Bank', '148', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('American Express Banking Corporation', '310', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Andhra Bank', '149', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Andhra Pradesh Grameena Vikas Bank', '267', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Andhra Pragathi Grameena Bank', '268', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Arunachal Pradesh Rural Bank', '269', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Aryavart Bank', '270', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Assam Gramin Vikash Bank', '266', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Au Small Finance Bank', '244', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Australia and New Zealand Banking Group Ltd.', '311', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Axis Bank', '180', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Bandan Bank', '196', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Bandhan Bank', '238', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Bangiya Gramin Vikash Bank Bank', '271', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Bank of America', '313', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Bank of Bahrain & Kuwait B.S.C.', '314', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Bank of Baroda', '150', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Bank of Ceylon', '315', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Bank of China', '316', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Bank of India', '151', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Bank of Maharashtra', '152', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Bank of Nova Scotia', '317', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Barclays Bank Plc.', '312', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Barclays Bank', '187', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Baroda Gujarat Gramin Bank', '272', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Baroda Rajasthan Kshetriya Grami Bank', '273', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Baroda UP Bank', '274', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('BNP Paribas', '318', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Canara Bank', '153', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Capital Small Finance Bank', '245', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Catholic Syrian Bank', '168', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Central Bank of India', '154', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Chaitanya Godavari GB Bank', '275', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Chhattisgarh Rajya Gramin Bank', '276', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Citibank N.A.', '319', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Citibank', '189', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('City Union Bank', '169', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Coastal Local Area Bank', '242', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Cooperatieve Rabobank U.A./ Coöperatieve Centrale Raiffeisen-Boerenleenbank B.A.', '320', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Corporation Bank', '155', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Credit Agricole Corporate & Investment Bank', '321', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Credit Suisse AG', '322', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('CSB Bank', '239', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('CTBC Bank Co. Ltd.', '323', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Dakshin Bihar Gramin Bank', '277', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('DBS Bank India Limited', '324', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('DBS Bank', '190', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('DCB Bank', '240', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Dena Bank', '156', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Deutsche Bank A.G.', '325', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Deutsche Bank', '191', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Development Credit Bank', '181', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Dhanlaxmi Bank', '170', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Dhanlaxmi Bank', '241', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Doha Bank Q.P.S.C', '326', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Ellaquai Dehati Bank', '278', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Emirates NBD Bank PJSC', '327', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Equitas Bank', '236', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Equitas Small Finance Bank', '247', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('ESAF Small Finance Bank', '248', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Export-Import Bank of India', '263', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Federal Bank', '171', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Fin Growth Co-Op bank Ltd', '199', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Fincare Small Finance Bank', '246', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('FINO Payments Bank', '258', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('First Abu Dhabi Bank PJSC', '328', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('FirstRand Bank Limited', '329', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('HDFC Bank', '182', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Himachal Pradesh Gramin Bank', '279', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Hong Kong and Shanghai Banking Corporation Limited', '330', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('HSBC', '192', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('ICICI Bank', '183', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('IDBI Bank Ltd.', '157', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('IDFC Bank', '195', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('India Post Payments Bank', '257', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Indian Bank', '158', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Indian Overseas Bank', '159', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('IndusInd Bank', '184', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Industrial & Commercial Bank of China Ltd.', '331', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Industrial Bank of Korea', '332', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('J&K Grameen Bank', '280', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('J.P. Morgan Chase Bank N.A.', '333', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Jammu & Kashmir Bank', '172', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Jana Small Finance Bank', '253', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Jharkhand Rajya Gramin Bank', '353', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Jio Payments Bank', '260', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('JSC VTB Bank', '334', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Karnataka Bank', '173', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Karnataka Gramin Bank', '281', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Karnataka Vikas Gramin Bank', '282', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Karur Vysya Bank', '174', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('KEB Hana Bank', '335', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Kerala Gramin Bank', '283', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Kookmin Bank', '336', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Kotak Mahindra Bank', '185', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Krishna Bhima Samruddhi Bank', '243', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Krung Thai Bank Public Co. Ltd. $', '337', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Lakshmi Vilas Bank', '175', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Madhya Pradesh Gramin Bank', '284', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Madhyanchal Gramin Bank', '285', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Maharashtra Gramin Bank', '286', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Manipur Rural Bank', '287', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Mashreq bank PSC', '338', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Meghalaya Rural Bank', '288', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Mizoram Rural Bank', '289', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Mizuho Bank Ltd.', '339', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('MUFG Bank Ltd.', '340', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Nagaland Rural Bank', '290', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Nainital Bank', '176', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('National Bank for Agriculture and Rural Development Bank', '262', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('National Housing Bank', '264', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('NatWest Markets Plc', '341', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('North East Small finance Bank', '252', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('NSDL Payments Bank', '261', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Odisha Gramya Bank', '291', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Oriental Bank of Commerce', '160', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Paschim Banga Gramin Bank', '292', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Paytm Payments Bank', '259', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Prathama U.P. Gramin Bank', '293', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('PT Bank Maybank Indonesia TBK', '342', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Puduvai Bharathiar Grama Bank', '294', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Punjab and Sind Bank', '161', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Punjab Gramin Bank', '295', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Punjab National Bank', '162', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Qatar National Bank (Q.P.S.C.)', '343', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Rajasthan Marudhara Gramin Bank', '296', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Ratnakar Bank', '177', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('RBL Bank', '237', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Royal Bank of Scotland', '193', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Saptagiri Grameena Bank', '297', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Saraswat Bank', '200', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Sarva Haryana Gramin Bank', '298', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Saurashtra Gramin Bank', '299', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Sberbank', '344', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('SBM Bank (India) Limited', '345', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Shinhan Bank', '346', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Shivalik Small Finance Bank', '254', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Small Industries Development Bank of India', '265', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Societe Generale India', '347', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Sonali Bank Ltd. %', '348', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('South Indian Bank', '178', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Standard Chartered Bank', '194', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Standard Chartered Bank', '349', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('State Bank of Bikaner & Jaipur', '143', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('State Bank of Hyderabad', '144', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('State Bank of India', '142', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('State Bank of Mysore', '145', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('State Bank of Patiala', '146', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('State Bank of Travancore', '147', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Sumitomo Mitsui Banking Corporation', '350', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Suryoday Small Finance Bank', '249', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Syndicate Bank', '163', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Tamil Nadu Grama Bank', '300', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Tamilnad Mercantile Bank', '179', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Telangana Grameena Bank', '301', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Tripura Gramin Bank', '302', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('UCO Bank', '164', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Ujjivan Small Finance Bank', '250', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Union Bank of India', '165', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('United Bank of India', '166', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('United Overseas Bank Limited', '351', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Unity Small Finance Bank', '255', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Utkal Grameen Bank', '304', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Utkarsh Small Finance Bank', '251', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Uttar Bihar Gramin Bank', '303', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Uttarakhand Gramin Bank', '307', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Uttarbanga Kshetriya Gramin Bank', '305', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Vidharbha Konkan Gramin Bank', '306', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Vijaya Bank', '167', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Woori Bank', '352', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Yes Bank', '186', '1', '17-05-2023', 'Priyaraj');
INSERT INTO PrimaryBank (BankName, BankID, activeStatus, createdOn, createdBy) VALUES ('Others', '235', '1', '17-05-2023', 'Priyaraj');
