-- ref_lender_config inserts
select * from ref_lender_config where lenderid = 10 and  OccupationTypeId = 1;
-- producttypeid = 1 and between 5L to 75L
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,1,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,1,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,1,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,1,1);

-- producttypeid = 2
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,2,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,2,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,2,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,2,1);

-- producttypeid = 4
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,4,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,4,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,4,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,4,1);

-- producttypeid = 5
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,5,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,5,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,5,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,5,1);

-------------------
select * from ref_lender_config where lenderid = 10 and  OccupationTypeId = 2;
-- producttypeid = 1 and occupationtypeid = 2 and between 5L to 75L
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,1,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,1,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,1,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,1,2);

-- producttypeid = 2
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,2,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,2,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,2,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,2,2);

-- producttypeid = 4
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,4,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,4,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,4,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,4,2);

-- producttypeid = 5
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,5,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,5,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,5,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,5,2);
-- --------------------------------------
-- ----------------------------
select * from ref_lender_config where lenderid = 10 and  OccupationTypeId = 3;
-- producttypeid = 1 and occupationtypeid = 3 and between 5L to 75L and maximumTenure = 240
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,240,0,24,59,60,1,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,240,0,24,59,60,1,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,240,0,24,59,60,1,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,240,0,24,59,60,1,3);

-- producttypeid = 2
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,240,0,24,59,60,2,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,240,0,24,59,60,2,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,240,0,24,59,60,2,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,240,0,24,59,60,2,3);

-- producttypeid = 4
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,240,0,24,59,60,4,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,240,0,24,59,60,4,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,240,0,24,59,60,4,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,240,0,24,59,60,4,3);

-- producttypeid = 5
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,240,0,24,59,60,5,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,240,0,24,59,60,5,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,240,0,24,59,60,5,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,240,0,24,59,60,5,3);
-- ---------------------------------------
-- For producttypeid insert queries applied on 7th February 2023 by Priyaraj
select * from ref_lender_config where lenderid = 10 and  OccupationTypeId = 2 and productTypeId = 6;
-- producttypeid = 6 and between 5L to 75L and OccupationTypeId = 2 
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,180,0,24,59,60,6,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,180,0,24,59,60,6,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,180,0,24,59,60,6,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,180,0,24,59,60,6,2);

-- producttypeid = 6 and between 5L to 75L and OccupationTypeId = 3
select * from ref_lender_config where lenderid = 10 and  OccupationTypeId = 3 and productTypeId = 6;
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,180,0,24,59,60,6,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,180,0,24,59,60,6,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,180,0,24,59,60,6,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,180,0,24,59,60,6,3);

-- producttypeid = 7 and between 5L to 75L and OccupationTypeId = 3
select * from ref_lender_config where lenderid = 10 and  OccupationTypeId = 3 and productTypeId = 7;
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,180,0,24,59,60,7,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,180,0,24,59,60,7,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,180,0,24,59,60,7,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,180,0,24,59,60,7,3);

-- producttypeid = 7 and between 5L to 75L and OccupationTypeId = 2
select * from ref_lender_config where lenderid = 10 and  OccupationTypeId = 2 and productTypeId = 7;
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,180,0,24,59,60,7,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,180,0,24,59,60,7,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,180,0,24,59,60,7,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,180,0,24,59,60,7,2);

-- scripts updated after clarification for citydivision
select * from ref_lender_citydivision where state ='Andhra Pradesh';
INSERT INTO `staging`.`ref_lender_citydivision` (`cityDivisionlenderId`, `cityDivision`, `state`, `lenderid`, `activestatus`, `createdon`, `updatedon`, `createdby`, `updatedby`) VALUES ('1013', 'Tenali', 'Andhra Pradesh', '10', '1', '2023-02-10 13:45:55', '2023-02-10 13:45:55', 'Vastu', 'Vastu');
INSERT INTO `staging`.`ref_lender_citydivision` (`cityDivisionlenderId`, `cityDivision`, `state`, `lenderid`, `activestatus`, `createdon`, `updatedon`, `createdby`, `updatedby`) VALUES ('1014', 'Narasaraopet', 'Andhra Pradesh', '10', '1', '2023-02-10 13:45:55', '2023-02-10 13:45:55', 'Vastu', 'Vastu');
INSERT INTO `staging`.`ref_lender_citydivision` (`cityDivisionlenderId`, `cityDivision`, `state`, `lenderid`, `activestatus`, `createdon`, `updatedon`, `createdby`, `updatedby`) VALUES ('1015', 'New Delhi', 'Delhi', '10', '1', '2023-02-10 13:45:55', '2023-02-10 13:45:55', 'Vastu', 'Vastu');
INSERT INTO `staging`.`ref_lender_citydivision` (`cityDivisionlenderId`, `cityDivision`, `state`, `lenderid`, `activestatus`, `createdon`, `updatedon`, `createdby`, `updatedby`) VALUES ('1017', 'Junagadh', 'Gujarat', '10', '1', '2023-02-10 13:57:55', '2023-02-10 13:57:55', 'Vastu', 'Vastu');
select * from ref_lender_citydivision where state ='Maharashtra';
INSERT INTO `staging`.`ref_lender_citydivision` (`cityDivisionlenderId`, `cityDivision`, `state`, `lenderid`, `activestatus`, `createdon`, `updatedon`, `createdby`, `updatedby`) VALUES ('1016', 'Malegaon', 'Maharashtra', '10', '1', '2023-02-10 14:05:55', '2023-02-10 14:05:55', 'Vastu', 'Vastu');
INSERT INTO `staging`.`ref_lender_citydivision` (`cityDivisionlenderId`, `cityDivision`, `state`, `lenderid`, `activestatus`, `createdon`, `updatedon`, `createdby`, `updatedby`) VALUES ('1018', 'Bhusaval', 'Maharashtra', '10', '1', '2023-02-10 14:05:55', '2023-02-10 14:05:55', 'Vastu', 'Vastu');
INSERT INTO `staging`.`ref_lender_citydivision` (`cityDivisionlenderId`, `cityDivision`, `state`, `lenderid`, `activestatus`, `createdon`, `updatedon`, `createdby`, `updatedby`) VALUES ('1019', 'Pandharpur', 'Maharashtra', '10', '1', '2023-02-10 14:24:55', '2023-02-10 14:24:55', 'Vastu', 'Vastu');
INSERT INTO `staging`.`ref_lender_citydivision` (`cityDivisionlenderId`, `cityDivision`, `state`, `lenderid`, `activestatus`, `createdon`, `updatedon`, `createdby`, `updatedby`) VALUES ('1020', 'Kapurthala', 'Punjab', '10', '1', '2023-02-10 14:24:55', '2023-02-10 14:24:55', 'Vastu', 'Vastu');
INSERT INTO `staging`.`ref_lender_citydivision` (`cityDivisionlenderId`, `cityDivision`, `state`, `lenderid`, `activestatus`, `createdon`, `updatedon`, `createdby`, `updatedby`) VALUES ('1021', 'Pollachi', 'Tamil Nadu', '10', '1', '2023-02-10 14:24:55', '2023-02-10 14:24:55', 'Vastu', 'Vastu');
INSERT INTO `staging`.`ref_lender_citydivision` (`cityDivisionlenderId`, `cityDivision`, `state`, `lenderid`, `activestatus`, `createdon`, `updatedon`, `createdby`, `updatedby`) VALUES ('1022', 'Kovilpatti', 'Tamil Nadu', '10', '1', '2023-02-10 14:24:55', '2023-02-10 14:24:55', 'Vastu', 'Vastu');
INSERT INTO `staging`.`ref_lender_citydivision` (`cityDivisionlenderId`, `cityDivision`, `state`, `lenderid`, `activestatus`, `createdon`, `updatedon`, `createdby`, `updatedby`) VALUES ('1023', 'Hanamkonda', 'Telangana', '10', '1', '2023-02-10 14:24:55', '2023-02-10 14:24:55', 'Vastu', 'Vastu');

-- For producttypeid insert queries applied on 22nd February 2023 by Priyaraj for lenderid = 0 as final page of applicationneeds those values
select count(1) from ref_lender_config where lenderid = 0  and productTypeId in (6,7);
-- producttypeid = 6 and between 0 to 999999999 and OccupationTypeId = 2 for lender 0
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,1,1,0,999999999,0,0,0,360,0,21,99,70,6,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,2,1,0,999999999,0,0,0,360,0,21,99,70,6,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,3,1,0,999999999,0,0,0,360,0,21,99,70,6,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,4,1,0,999999999,0,0,0,360,0,21,99,70,6,2);

-- producttypeid = 6 and between 0 to 999999999 and OccupationTypeId = 3 for lender 0
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,1,1,0,999999999,0,0,0,360,0,21,99,70,6,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,2,1,0,999999999,0,0,0,360,0,21,99,70,6,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,3,1,0,999999999,0,0,0,360,0,21,99,70,6,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,4,1,0,999999999,0,0,0,360,0,21,99,70,6,3);

-- producttypeid = 7 and between 0 to 999999999 and OccupationTypeId = 2 for lender 0
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,1,1,0,999999999,0,0,0,360,0,21,99,70,7,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,2,1,0,999999999,0,0,0,360,0,21,99,70,7,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,3,1,0,999999999,0,0,0,360,0,21,99,70,7,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,4,1,0,999999999,0,0,0,360,0,21,99,70,7,2);

-- producttypeid = 7 and between 0 to 999999999 and OccupationTypeId = 3 for lender 0
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,1,1,0,999999999,0,0,0,360,0,21,99,70,7,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,2,1,0,999999999,0,0,0,360,0,21,99,70,7,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,3,1,0,999999999,0,0,0,360,0,21,99,70,7,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (0,4,1,0,999999999,0,0,0,360,0,21,99,70,7,3);


