-- ref_lender_config inserts
select * from ref_lender_config where lenderid = 10 and  OccupationTypeId = 1;
-- producttypeid = 1 and between 5L to 75L
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,1,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,1,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,1,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,1,1);

-- producttypeid = 2
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,2,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,2,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,2,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,2,1);

-- producttypeid = 4
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,4,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,4,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,4,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,4,1);

-- producttypeid = 5
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,5,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,5,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,5,1);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,5,1);

-------------------
select * from ref_lender_config where lenderid = 10 and  OccupationTypeId = 2;
-- producttypeid = 1 and occupationtypeid = 2 and between 5L to 75L
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,1,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,1,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,1,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,1,2);

-- producttypeid = 2
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,2,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,2,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,2,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,2,2);

-- producttypeid = 4
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,4,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,4,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,4,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,4,2);

-- producttypeid = 5
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,1,3,240,0,21,59,60,5,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,1,3,240,0,21,59,60,5,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,1,3,240,0,21,59,60,5,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,1,3,240,0,21,59,60,5,2);
-- --------------------------------------
-- ----------------------------
select * from ref_lender_config where lenderid = 10 and  OccupationTypeId = 3;
-- producttypeid = 1 and occupationtypeid = 3 and between 5L to 75L and maximumTenure = 240
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,240,0,24,59,60,1,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,240,0,24,59,60,1,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,240,0,24,59,60,1,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,240,0,24,59,60,1,3);

-- producttypeid = 2
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,240,0,24,59,60,2,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,240,0,24,59,60,2,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,240,0,24,59,60,2,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,240,0,24,59,60,2,3);

-- producttypeid = 4
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,240,0,24,59,60,4,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,240,0,24,59,60,4,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,240,0,24,59,60,4,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,240,0,24,59,60,4,3);

-- producttypeid = 5
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,240,0,24,59,60,5,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,240,0,24,59,60,5,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,240,0,24,59,60,5,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,240,0,24,59,60,5,3);
-- ---------------------------------------
-- For producttypeid insert queries applied on 7th February 2023 by Priyaraj
select * from ref_lender_config where lenderid = 10 and  OccupationTypeId = 2 and productTypeId = 6;
-- producttypeid = 6 and between 5L to 75L and OccupationTypeId = 2 
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,180,0,24,59,60,6,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,180,0,24,59,60,6,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,180,0,24,59,60,6,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,180,0,24,59,60,6,2);

-- producttypeid = 6 and between 5L to 75L and OccupationTypeId = 3
select * from ref_lender_config where lenderid = 10 and  OccupationTypeId = 3 and productTypeId = 6;
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,180,0,24,59,60,6,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,180,0,24,59,60,6,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,180,0,24,59,60,6,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,180,0,24,59,60,6,3);

-- producttypeid = 7 and between 5L to 75L and OccupationTypeId = 3
select * from ref_lender_config where lenderid = 10 and  OccupationTypeId = 3 and productTypeId = 7;
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,180,0,24,59,60,7,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,180,0,24,59,60,7,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,180,0,24,59,60,7,3);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,180,0,24,59,60,7,3);

-- producttypeid = 7 and between 5L to 75L and OccupationTypeId = 2
select * from ref_lender_config where lenderid = 10 and  OccupationTypeId = 2 and productTypeId = 7;
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,1,1,500000,7500000,12000,3,3,180,0,24,59,60,7,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,2,1,500000,7500000,12000,3,3,180,0,24,59,60,7,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,3,1,500000,7500000,12000,3,3,180,0,24,59,60,7,2);
INSERT INTO `staging`.`ref_lender_config` (`lenderId`,`cityTierId`,`lendingcategoryid`,`minimumLendingAmount`,`maximumLendingAmount`,`minimumEarningsAmount`,`minimumJobExperience`,`minimumProfExperience`,`maximumTenure`,`useGrossPay`,`minimumAge`,`maximumAge`,`maximumAgeAtMaturity`,`productTypeId`,`OccupationTypeId`) VALUES (10,4,1,500000,7500000,12000,3,3,180,0,24,59,60,7,2);