use staging;
-- Business requirement of 'Addition of occupationtype column in lender_product_loan table' table -- Done by Priyaraj on March 17,2023
ALTER TABLE lender_product_loan ADD occupationtypeId TINYINT;
select * from lender_product_loan where lenderid = 0  and producttypeid = 1 and loantypeid = 2
order by producttypeid;

UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '121');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '128');

select max(lenderproductloanid) from lender_product_loan;

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('164', '10', '1', '1', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('165', '10', '1', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('166', '10', '1', '1', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('167', '10', '1', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('168', '10', '2', '1', '2023-03-17 15:27:33', '2023-03-17 15:27:33', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '123');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '129');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('169', '10', '2', '2', '2023-03-17 15:27:33', '2023-03-17 15:27:33', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('170', '10', '2', '1', '2023-03-17 15:27:33', '2023-03-17 15:27:33', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('171', '10', '2', '2', '2023-03-17 15:27:33', '2023-03-17 15:27:33', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('172', '10', '3', '1', '2023-03-17 13:11:02', '2023-03-17 13:11:02', 'Vastu', 'Vastu', '1', '1', '1', '0', '2');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '140');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '141');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('173', '10', '3', '2', '2023-03-17 13:11:02', '2023-03-17 13:11:02', 'Vastu', 'Vastu', '1', '1', '1', '0', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('174', '10', '3', '1', '2023-03-17 13:11:02', '2023-03-17 13:11:02', 'Vastu', 'Vastu', '1', '1', '1', '0', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('175', '10', '3', '1', '2023-03-17 13:11:02', '2023-03-17 13:11:02', 'Vastu', 'Vastu', '1', '1', '1', '0', '3');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('176', '10', '4', '1', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '125');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '131');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('177', '10', '4', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('178', '10', '4', '1', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('179', '10', '4', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('184', '10', '6', '3', '2023-03-15 10:32:53', '2023-03-15 10:32:53', 'Vastu', 'Vastu', '1', '1', '6', '1', '2');
UPDATE `staging`.`lender_product_loan` SET `applicability` = '0', `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '136');
UPDATE `staging`.`lender_product_loan` SET `applicability` = '0', `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '161');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('185', '10', '6', '2', '2023-03-15 10:32:53', '2023-03-15 10:32:53', 'Vastu', 'Vastu', '1', '1', '6', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('186', '10', '6', '3', '2023-03-15 10:32:53', '2023-03-15 10:32:53', 'Vastu', 'Vastu', '1', '1', '6', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('187', '10', '6', '2', '2023-03-15 10:32:53', '2023-03-15 10:32:53', 'Vastu', 'Vastu', '1', '1', '6', '1', '3');


INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('180', '10', '5', '1', '2023-03-17 15:27:33', '2023-03-17 15:27:33', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '126');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '132');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('181', '10', '5', '2', '2023-03-17 15:27:33', '2023-03-17 15:27:33', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('182', '10', '5', '1', '2023-03-17 15:27:33', '2023-03-17 15:27:33', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('183', '10', '5', '1', '2023-03-17 15:27:33', '2023-03-17 15:27:33', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('188', '10', '7', '3', '2023-03-17 00:50:58', '2023-03-17 00:50:58', 'Vastu', 'Vastu', '1', '1', '7', '1', '2');
UPDATE `staging`.`lender_product_loan` SET `applicability` = '0', `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '137');
UPDATE `staging`.`lender_product_loan` SET `applicability` = '0', `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '162');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('189', '10', '7', '2', '2023-03-17 00:50:58', '2023-03-17 00:50:58', 'Vastu', 'Vastu', '1', '1', '7', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('190', '10', '7', '3', '2023-03-17 00:50:58', '2023-03-17 00:50:58', 'Vastu', 'Vastu', '1', '1', '7', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('191', '10', '7', '3', '2023-03-17 00:50:58', '2023-03-17 00:50:58', 'Vastu', 'Vastu', '1', '1', '7', '1', '3');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('192', '10', '99', '1', '2023-02-02 13:11:57', '2023-02-02 13:11:57', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '142');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('193', '10', '99', '1', '2023-02-02 13:11:57', '2023-02-02 13:11:57', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');

select * from lender_product_loan where lenderid = 11  and producttypeid = 3;

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('194', '11', '1', '1', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '1');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('195', '11', '1', '2', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '1');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('196', '11', '1', '1', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('197', '11', '1', '2', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('198', '11', '1', '1', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('199', '11', '1', '2', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');

--
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('200', '11', '2', '1', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '1');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('201', '11', '2', '2', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '1');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('202', '11', '2', '1', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('203', '11', '2', '2', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('204', '11', '2', '1', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('205', '11', '2', '2', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
--
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('206', '11', '4', '1', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '1');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('207', '11', '4', '2', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '1');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('208', '11', '4', '1', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('209', '11', '4', '2', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('210', '11', '4', '1', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('211', '11', '4', '2', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
--
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('212', '11', '4', '1', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '1');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('213', '11', '4', '2', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '1');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('214', '11', '4', '1', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('215', '11', '4', '2', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('210', '11', '4', '1', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('211', '11', '4', '2', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('218', '11', '3', '1', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '0', '1');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('219', '11', '3', '2', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '0', '1');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('220', '11', '3', '1', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '0', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('221', '11', '3', '2', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '0', '2');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('222', '11', '3', '1', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '0', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('223', '11', '3', '2', '2023-01-24 15:24:56', '2023-01-24 15:24:56', 'Vastu', 'Vastu', '1', '1', '1', '0', '3');
--
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '163');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('224', '11', '99', '1', '2023-03-17 13:11:57', '2023-03-17 13:11:57', 'Vastu', 'Vastu', '1', '1', '1', '0', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('225', '11', '99', '1', '2023-03-17 13:11:57', '2023-03-17 13:11:57', 'Vastu', 'Vastu', '1', '1', '1', '0', '3');

select * from lender_product_loan where lenderid = 11 and applicability = 0
order by producttypeid;
UPDATE `staging`.`lender_product_loan` SET `applicability` = '0', `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '145');
UPDATE `staging`.`lender_product_loan` SET `applicability` = '0', `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '147');

UPDATE `staging`.`lender_product_loan` SET `applicability` = '0', `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '146');
UPDATE `staging`.`lender_product_loan` SET `applicability` = '0', `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '148');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('226', '11', '6', '3', '2023-03-17 10:32:53', '2023-03-17 10:32:53', 'Vastu', 'Vastu', '1', '1', '6', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('227', '11', '6', '2', '2023-03-17 10:32:53', '2023-03-17 10:32:53', 'Vastu', 'Vastu', '1', '1', '6', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('228', '11', '6', '3', '2023-03-17 10:32:53', '2023-03-17 10:32:53', 'Vastu', 'Vastu', '1', '1', '6', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('229', '11', '6', '2', '2023-03-17 10:32:53', '2023-03-17 10:32:53', 'Vastu', 'Vastu', '1', '1', '6', '1', '2');

select * from lender_product_loan where lenderid = 0 and applicability = 0

UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '1');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '2');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '3');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '4');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '5');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '6');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '43');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '44');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '45');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '46');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '47');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '48');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '143');
UPDATE `staging`.`lender_product_loan` SET `occupationtypeId` = '1' WHERE (`lenderproductloanid` = '144');

-- Need to add occupationtypeid 2 and 3
select * from lender_product_loan where lenderid in (0) and producttypeid = 7 and applicability = 1;

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('230', '0', '1', '1', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('231', '0', '1', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('232', '0', '1', '1', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('233', '0', '1', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('234', '0', '2', '1', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('235', '0', '2', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('236', '0', '2', '1', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('237', '0', '2', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('238', '0', '3', '1', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('239', '0', '3', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('240', '0', '3', '1', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('241', '0', '3', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('242', '0', '4', '1', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('243', '0', '4', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('244', '0', '4', '1', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('245', '0', '4', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('246', '0', '5', '1', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('247', '0', '5', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('248', '0', '5', '1', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('249', '0', '1', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');


INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('250', '0', '6', '3', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('251', '0', '6', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('252', '0', '6', '3', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('253', '0', '6', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('254', '0', '6', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '1');

INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('255', '0', '7', '3', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('256', '0', '7', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '3');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('257', '0', '7', '3', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('258', '0', '7', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('259', '0', '7', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '1');

DELETE FROM `staging`.`lender_product_loan` WHERE (`lenderproductloanid` = '249');
INSERT INTO `staging`.`lender_product_loan` (`lenderproductloanid`, `lenderid`, `producttypeid`, `loantypeid`, `created_on`, `updated_on`, `created_by`, `updated_by`, `activeStatus`, `loantypeforintcal`, `producttypeforintcal`, `applicability`, `occupationtypeId`) VALUES ('260', '0', '5', '2', '2023-03-17 15:28:51', '2023-03-17 15:28:51', 'Vastu', 'Vastu', '1', '1', '1', '1', '2');






