/*
-- Query: SELECT * FROM staging.ref_loan_lender where loanLenderid > 236
LIMIT 0, 1000

-- Date: 2023-04-11 11:42
*/
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (237,'Piramal Capital',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (238,'Housing and urban Development Corporation Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (239,'Indiabulls Housing Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (240,'PNB Housing Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (241,'Bajaj Housing Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (242,'Tata Capital Housing Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (243,'Can Fin Homes Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (244,'IIFL Home Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (245,'ICICI Home Finance Company Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (246,'Aadhar Housing Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (247,'Aditya Birla Housing Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (248,'REPCO Home Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (249,'GIC Housing Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (250,'Aavas Financiers Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (251,'Reliance Home Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (252,'Sundaram Home Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (253,'Mahindra Rural Housing Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (254,'Shriram Housing Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (255,'Aptus Value Housing Finance India Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (256,'Home First Finance Company India Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (257,'Fullerton India Home Finance Company Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (258,'Poonawalla Housing Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (259,'Edelweiss Housing Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (260,'Hinduja Housing Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (261,'Motilal Oswal Home Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (262,'Vastu Housing Finance Corporation Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (263,'India Shelter Finance Corporation Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (264,'Hero Housing Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (265,'Shubham Housing Development Finance Company',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (266,'Capri Global Housing Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (267,'Godrej Housing Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (268,'Muthoot Housing Finance Company Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (269,'IndoStar Home Finance Private Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (270,'Muthoot Homefin (India) Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (271,'Svatantra Micro Housing Finance Corporation Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (272,'Cent Bank Home Finance Limited ',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (273,'Karnataka Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (274,'Karnataka Vikas Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (275,'Kerala Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (276,'Madhya Pradesh Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (277,'Madhyanchal Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (278,'Maharashtra Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (279,'Manipur Rural Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (280,'Meghalaya Rural Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (281,'Mizoram Rural Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (282,'Nagaland Rural Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (283,'Odisha Gramya Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (284,'Paschim Banga Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (285,'Prathama U.P. Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (286,'Puduvai Bharathiar Grama Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (287,'Punjab Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (288,'Rajasthan Marudhara Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (289,'Saptagiri Grameena Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (290,'Sarva Haryana Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (291,'Saurashtra Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (292,'Tamil Nadu Grama Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (293,'Telangana Grameena Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (294,'Tripura Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (295,'Uttar Bihar Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (296,'Utkal Grameen Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (297,'Uttarbanga Kshetriya Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (298,'Vidharbha Konkan Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (299,'Uttarakhand Gramin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (300,'AB Bank Ltd.',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (301,'Abu Dhabi Commercial Bank PJSC',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (302,'American Express Banking Corporation',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (303,'Australia and New Zealand Banking Group Ltd.',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (304,'Barclays Bank Plc.',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (305,'Bank of America',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (306,'Bank of Bahrain & Kuwait B.S.C.',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (307,'Bank of Ceylon',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (308,'Bank of China',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (309,'Bank of Nova Scotia',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (310,'Citibank N.A.',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (311,'Cooperatieve Rabobank U.A./ Coöperatieve Centrale Raiffeisen-Boerenleenbank B.A.',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (312,'Credit Agricole Corporate & Investment Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (313,'Credit Suisse AG',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (314,'CTBC Bank Co., Ltd.',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (315,'DBS Bank India Limited',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (316,'Deutsche Bank A.G.',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (317,'Doha Bank Q.P.S.C',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (318,'Emirates NBD Bank PJSC',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (319,'First Abu Dhabi Bank PJSC',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (320,'FirstRand Bank Limited',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (321,'Hong Kong and Shanghai Banking Corporation Limited',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (322,'Industrial & Commercial Bank of China Ltd.',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (323,'Industrial Bank of Korea',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (324,'J.P. Morgan Chase Bank N.A.',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (325,'JSC VTB Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (326,'KEB Hana Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (327,'Kookmin Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (328,'Krung Thai Bank Public Co. Ltd. $',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (329,'Mashreq bank PSC',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (330,'Mizuho Bank Ltd.',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (331,'MUFG Bank, Ltd.',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (332,'NatWest Markets Plc',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (333,'PT Bank Maybank Indonesia TBK',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (334,'Qatar National Bank (Q.P.S.C.)',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (335,'Sberbank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (336,'SBM Bank (India) Limited',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (337,'Shinhan Bank',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (338,'Societe Generale India',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (339,'Sonali Bank Ltd. %',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (340,'Sumitomo Mitsui Banking Corporation',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (341,'United Overseas Bank Limited',NULL,NULL,NULL,NULL,1);
INSERT INTO `ref_loan_lender` (`loanLenderId`,`loanLenderName`,`createdOn`,`createdBy`,`updatedOn`,`updatedBy`,`activeStatus`) VALUES (342,'Woori Bank',NULL,NULL,NULL,NULL,1);
